/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Quotes {

    private static Reader reader;

    private  static String pathUrl="app/src/main/resources/quotes.JSON";

     static List<User> allQuotes;
public static void fromJson(String pathUrl)
        {
              int randomIndex= (int) (Math.random()*159);
            try {
                reader = Files.newBufferedReader(Paths.get(pathUrl));

            } catch (IOException error) {
                error.printStackTrace();
            }

            allQuotes = new Gson().fromJson(reader, new TypeToken<List<User>>() {}.getType());



            System.out.println(allQuotes.get(randomIndex).getText());

        }

    public  List<User> getAllQuotes() {
        return allQuotes;
    }

    public static String getPathUrl() {
        return pathUrl;
    }

    public static void main(String[] args) {
        fromJson(getPathUrl());

    }

}
