/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class QuotesFromFile {

    private static Reader reader;


     static List<Quote> allQuotes;
public static String fromJson(String pathUrl)
        {
              int randomIndex= (int) (Math.random()*159);
            try {
                reader = Files.newBufferedReader(Paths.get(pathUrl));

            } catch (IOException error) {
                error.printStackTrace();
            }

            allQuotes = new Gson().fromJson(reader, new TypeToken<List<Quote>>() {}.getType());



            return (allQuotes.get(randomIndex).getText());

        }

    public  List<Quote> getAllQuotes() {
        return allQuotes;
    }





}
